from pathlib import Path
import re
import subprocess


def _tracked_files() -> tuple[Path, ...]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        check=True,
        capture_output=True,
    )
    return tuple(Path(item.decode()) for item in result.stdout.split(b"\0") if item)


def test_repository_has_no_irrelevant_dotnet_language_example():
    forbidden = "c" + "#"
    roots = (
        Path("cv_agent"),
        Path("evals"),
        Path("knowledge"),
        Path("tests"),
        Path("README.md"),
    )
    matches = []
    for root in roots:
        paths = [root] if root.is_file() else root.rglob("*")
        for path in paths:
            if path.is_file() and path.suffix in {".py", ".md", ".yaml", ".jsonl"}:
                if forbidden in path.read_text(encoding="utf-8").casefold():
                    matches.append(str(path))

    assert matches == []


def test_public_project_evidence_uses_reviewed_https_sources():
    enerey = Path("knowledge/03_proyectos_enerey.md").read_text(encoding="utf-8")
    freelance = Path("knowledge/17_freelance_global_lugra.md").read_text(
        encoding="utf-8"
    )
    readme = Path("README.md").read_text(encoding="utf-8")

    for url in (
        "https://enereylatam.com/",
        "https://apps.apple.com/mx/app/enerey/id6736633080",
    ):
        assert url in enerey
        assert url in readme
    for url in ("https://www.lugramx.com/", "https://globalfls.com/"):
        assert url in freelance
        assert url in readme
    assert "© Gael Alguiar" in enerey
    assert "no demuestra por sí sola cada componente" in " ".join(enerey.split())


def test_public_repository_uses_current_verified_counts():
    assert sum(1 for _ in Path("knowledge").glob("*.md")) == 17
    assert sum(1 for _ in Path("evals/cv_agent_cases.jsonl").open()) == 125
    assert not Path("docs/VIDEO_DEMO_SCRIPT.md").exists()


def test_public_repository_excludes_internal_development_workflow_artifacts():
    text_suffixes = {
        ".md", ".py", ".yaml", ".yml", ".json", ".jsonl", ".txt",
        ".sh", ".html", ".css", ".js", ".example",
    }
    forbidden_paths = {
        "docs/" + "super" + "powers",
        "docs/azure_ai_search_" + "implementation_" + "plan.md",
    }
    forbidden_directory_names = {
        "scratch", "temporary", "." + "codex", "." + "claude",
    }
    forbidden_markers = tuple(
        value.casefold()
        for value in (
            "required sub-" + "skill",
            "agentic " + "workers",
            "super" + "powers:",
            "generated by " + "chatgpt",
            "generated by " + "claude",
            "generated by " + "codex",
            "chatgpt-" + "generated",
            "claude-" + "generated",
            "codex-" + "generated",
        )
    )

    findings = []
    for path in _tracked_files():
        if not path.is_file():
            continue
        relative = path.as_posix().removeprefix("./")
        folded_path = relative.casefold()
        if forbidden_directory_names.intersection(part.casefold() for part in path.parts):
            findings.append(relative)
            continue
        if any(folded_path == item or folded_path.startswith(f"{item}/") for item in forbidden_paths):
            findings.append(relative)
            continue
        if path.suffix.casefold() not in text_suffixes and path.name != ".env.example":
            continue
        text = path.read_text(encoding="utf-8", errors="ignore").casefold()
        if any(marker in text for marker in forbidden_markers):
            findings.append(relative)
        if re.search(r"/(?:users|home)/[a-z0-9._-]+/", text):
            findings.append(relative)

    assert sorted(set(findings)) == []


def test_public_material_has_no_personal_accounts_or_cloud_identifiers():
    text_suffixes = {
        ".md", ".py", ".yaml", ".yml", ".json", ".jsonl", ".txt",
        ".sh", ".html", ".css", ".js", ".example",
    }
    email_pattern = re.compile(
        r"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}", re.IGNORECASE
    )
    cloud_id_pattern = re.compile(
        r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b",
        re.IGNORECASE,
    )
    clearly_synthetic_domains = {"example.com"}
    clearly_synthetic_cloud_ids = {"123e4567-e89b-42d3-a456-426614174000"}
    findings = []

    for path in _tracked_files():
        if not path.is_file():
            continue
        if path.suffix.casefold() not in text_suffixes and path.name != ".env.example":
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        emails = email_pattern.findall(text)
        cloud_ids = cloud_id_pattern.findall(text)
        real_emails = [
            item for item in emails
            if not any(
                item.rsplit("@", 1)[1].casefold() == domain
                or item.rsplit("@", 1)[1].casefold().endswith(f".{domain}")
                for domain in clearly_synthetic_domains
            )
        ]
        real_cloud_ids = [
            item for item in cloud_ids
            if item.casefold() not in clearly_synthetic_cloud_ids
        ]
        if real_emails or real_cloud_ids:
            findings.append(str(path))

    assert findings == []


def test_local_markdown_links_resolve_to_public_repository_files():
    link_pattern = re.compile(r"!?\[[^]]*\]\(([^)]+)\)")
    missing = []
    repository_root = Path.cwd().resolve()
    tracked = {path.resolve() for path in _tracked_files()}

    for document in (Path("README.md"), *Path("docs").rglob("*.md")):
        text = document.read_text(encoding="utf-8")
        for target in link_pattern.findall(text):
            target = target.strip().split("#", 1)[0]
            if not target or target.startswith(("https://", "http://", "mailto:")):
                continue
            resolved = (document.parent / target).resolve()
            if (
                not resolved.is_relative_to(repository_root)
                or not resolved.exists()
                or resolved not in tracked
            ):
                missing.append(f"{document}:{target}")

    assert missing == []
